language: java
jdk:
  - oraclejdk8

env:
  - CUBRID_VERSION=9.1.0
  - CUBRID_VERSION=8.4.4
  - CUBRID_VERSION=8.4.3
  - CUBRID_VERSION=8.4.1

install: 
   - echo 'yes' | sudo add-apt-repository ppa:cubrid/cubrid
   - sudo apt-get update 
   - sudo apt-get install cubrid 
   - /etc/profile.d/cubrid.sh 
   - sudo apt-get install cubrid-demodb 
   - echo '/opt/'